- name: Setup GCP
  hosts: localhost
  environment:
    GCP_AUTH_KIND: "{{gcp_auth_kind}}"
    GCP_SERVICE_ACCOUNT_FILE: "{{ gcp_service_account_file }}"
    GCP_SCOPES: "{{gcp_scopes}}"

  tasks:
    # Add firewall rules for http
    - name: "Create http firewall rule"
      gce_net:
        name: default
        fwname: "default-allow-http"
        allowed: "tcp:80"
        state: "present"
        src_range: "0.0.0.0/0"
        project_id: "{{ gcp_project }}"
        target_tags: "http-server"
        credentials_file: "{{ gcp_service_account_file }}"
        service_account_email: "{{ gcp_service_account_email }}"
      when: cluster_state == "present"

    # Add firewall rules for https
    - name: "Create https firewall rule"
      gce_net:
        name: default
        fwname: "default-allow-https"
        allowed: "tcp:443"
        state: "present"
        src_range: "0.0.0.0/0"
        project_id: "{{ gcp_project }}"
        target_tags: "http-server"
        credentials_file: "{{ gcp_service_account_file }}"
        service_account_email: "{{ gcp_service_account_email }}"
      when: cluster_state == "present"